baseurl = "https://conoroneill.net/"
languageCode = "en-us"
title = "Cross Dominant"
theme = "casper"
Paginate = 10
disqusShortname = "crossdominant"
uglyUrls=false
publishdir = "docs"
rssLimit = 20

[permalinks]
  post="/:year/:month/:day/:slug/"

[params]
  githubName = "conoro"
  instagramName = "cwjoneill"
  otherblog = "https://conoroneill.com"
  linkedinName = "conoroneill"
  description = "Mixed laterality since 1968"
  google_analytics = "UA-88610-4"
  googleAnalyticsUserID = "UA-88610-4"
  cover = "images/ZXSpectrum48k.jpg"
  author = "Conor O'Neill"
  authorlocation = "Bandon, Cork, Ireland"
  authorwebsite = "https://conoroneill.net"
  bio= "Tech guy who likes running slowly"
  logo = "images/cross_dominant.png"



